###测试发送请求文件


### 1.获取基本信息
GET http://127.0.0.1:8081/GetDevInformation
Accept: application/json

###
### 2.获取AI处理模块状态
GET http://3512i894p8.goho.co/GetDevAnalyseModelStatus?Models=1
Accept: application/json

###3.提交AI分析请求
POST http://3512i894p8.goho.co/Analyse?Model=1
Content-Type: application/json

{
  "Actions":
  [
    {
      "Id":1234,	
      "Src":
      {
        "Type":0,	
        "Uri":"286.jpg"
      },
      "Dst":
      {
        "Type":0,
        "Uri":"286.jpg"
      }
    }

  ]
}
###
POST http://127.0.0.1:8081/Analyse?Model=1
Content-Type: application/json

{
"Actions":
[
{
"Id":1234,
"Src":
{
"Type":0,
"Uri":"286.jpg"
},
"Dst":
{
"Type":0,
"Uri":"286.jpg"
}
}

]
}

###4.重新加载AI处理模块请求
PUT http://3512i894p8.goho.co/ReloadAnalyseModels
Accept: application/json


###5.提交AI模块资源初始化请求
PUT http://3512i894p8.goho.co/InitAnalyseModel
Accept: application/json

###6.提交AI模块资源释放请求
PUT http://3512i894p8.goho.co/DeInitAnalyseModel
Accept: application/json
###6.提交AI模块资源释放请求
PUT http://127.0.0.1:8081/DeInitAnalyseModel
Accept: application/json